#This file stores configuration options for Iris, such as the currently active shaderpack
#Fri Aug 14 18:31:47 BST 2026
allowUnknownShaders=false
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=true
maxShadowRenderDistance=32
shaderPack=
